CREATE TABLE CURS_ON_DATE (
  ID      NUMBER(10)    NOT NULL,
  NAME    VARCHAR2(50 BYTE),
  NOM     NUMBER(10, 0),
  CURS    NUMBER(10, 4),
  CODE    NUMBER(5, 0),
  CH_CODE VARCHAR2(50 BYTE),
  ONDATE  DATE);

ALTER TABLE CURS_ON_DATE ADD (
  CONSTRAINT CURS_ON_DATE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CURS_ON_DATE_SEQ START WITH 1;


CREATE OR REPLACE TRIGGER CURS_ON_DATE_bir
BEFORE INSERT ON CURS_ON_DATE
FOR EACH ROW

BEGIN
  SELECT CURS_ON_DATE_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;